[pytest]
testpaths = api
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: быстрая проверка ключевых эндпоинтов
    regression: полный регрессионный прогон
    product: тесты модуля product
    user: тесты модуля user
    users: тесты модуля users
    auth: тесты авторизации